set(FFMPEG_libavcodec_FOUND 1)
set(FFMPEG_libavformat_FOUND 1)
set(FFMPEG_libavutil_FOUND 1)
set(FFMPEG_libswscale_FOUND 1)
set(FFMPEG_libavresample_FOUND 1)

set(FFMPEG_libavcodec_VERSION 57.64.101)
set(FFMPEG_libavformat_VERSION 57.56.100)
set(FFMPEG_libavutil_VERSION 55.34.100)
set(FFMPEG_libswscale_VERSION 4.2.100)
set(FFMPEG_libavresample_VERSION 3.1.0)
