set(FFMPEG_libavcodec_FOUND 1)
set(FFMPEG_libavformat_FOUND 1)
set(FFMPEG_libavutil_FOUND 1)
set(FFMPEG_libswscale_FOUND 1)
set(FFMPEG_libavresample_FOUND 1)

set(FFMPEG_libavcodec_VERSION 58.35.100)
set(FFMPEG_libavformat_VERSION 58.20.100)
set(FFMPEG_libavutil_VERSION 56.22.100)
set(FFMPEG_libswscale_VERSION 5.3.100)
set(FFMPEG_libavresample_VERSION 4.0.0)
